---
title: "Classification"
author: "Stefan Haböck & Bernhard Mayr"
date: "30 11 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dependencies
```{r dependencies, warning=FALSE, message=FALSE}
library(dplyr)
library(class)
library(lolR)
```

```{r data}
ctd <- read.table("./CtD.csv", sep=";", header=TRUE, strip.white=TRUE) %>%
  tibble::as_tibble()
ttd <- read.table("./ttd.csv", sep=",", header=FALSE, strip.white=TRUE) %>%
  tibble::as_tibble()

names(ctd) <- c("lectureName", "isTechnology", "isInterdisciplinary", "isMedia", "isBiology")

data <- bind_cols(ctd, ttd)
```

```{r split}
trainingData = .7 # 70% Training Data / 30% Test Data
dt = sort(sample(nrow(data), nrow(data) * trainingData))
train <- data[dt,]
test <- data[-dt,]
```

```{r rocchio}
features = train %>% select(6:ncol(train))
features_test = test %>% select(6:ncol(test))
labels = train$isTechnology
model <- lol.classify.nearestCentroid(features, labels)
result <- predict(model, features_test);
measurePrecisionRecall(result, test$isTechnology)

measurePrecisionRecall <- function(predict, actual_labels){
  precision <- sum(predict & actual_labels) / sum(predict)
  recall <- sum(predict & actual_labels) / sum(actual_labels)
  fmeasure <- 2 * precision * recall / (precision + recall)

  cat('precision:  ')
  cat(precision * 100)
  cat('%')
  cat('\n')
  
  cat('recall:     ')
  cat(recall * 100)
  cat('%')
  cat('\n')


  cat('f-measure:  ')
  cat(fmeasure * 100)
  cat('%')
  cat('\n')
}
```

```{r knn}
features = train %>% select(6:ncol(train))
features_test = test %>% select(6:ncol(test))

labels = train$isTechnology
test_labels <- test$isTechnology
help(knn)
length(features)
length(labels)
train_knn <- knn(features,features_test,cl=labels,k=5);train_knn
tab <- table(train_knn,test_labels);tab
precision = (tab[2,2]/colSums(tab)))* 100;precision
recall = (tab[2,2]/(sum(rowSums(2))))* 100;recall
f-measure = ((1/precision+1/recall)/2)^-1* 100
accuracy <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}
accuracy(tab)
```